apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  #labels:
   #app:
spec:
  replicas: 2 #broji replika ako dode do pada jedne da druga preuzme pa je down time miniamalan
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: rohalr/service1:latest
        ports:
        - containerPort: 8080
      imagePullSecret:
      -name: mysecret  
#dodatak za secret key
  env:
  - name: service_1_username
    valueFrom:
     secretKeyRef: service1-secret
     key: my-username
     
  - name: service_1_password
    valueFrom:
     secretKeyRef: service1-secret
     key: my-password


---
#Service moze odovojeno ali istraživanjem sam primjetio da deployment i service(SVC) idu zajedno.
#SVC dodjeljuje premanet IP adresa podova(ako Pod umre i dode drugi imat če istu ip ardresu u protivnom morali bi ponovno dodjelit ip adresu i sve ponovno configurirat).
apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
