apiVersion: v1
kind: Secret
metadata:
  name: service1-secret
type: Opaque
data:
  my-username: YWRtaW4=           #echo -n 'username'| base64
  my-password: MWYyZDFlMmU2N2Rm   #echo -n 'password'| base64 

  # kreiranje secreta:
  #cd u file u kojem se nalazi 
  # kubectl apply service1-secret.yaml
  #za provjeru : kubectl get secret