name: ci

on:
  push:
    branches:
      - 'main'
 
  pull_request:
    branches:
      -  'main'
    paths: 
       -'service1/**'
       -'Projectavl/.github/workflows/buildimage.yaml'     
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERPWD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: v1.0
          push: true
          tags: rohalr/roha_docker:service1
