name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build Service1 Docker Image
      run: |
        docker build -t service1 -f service1/Dockerfile .
    - name: Build Service2 Docker Image
      run: |
        docker build -t service2  -f service2/Dockerfile .
    #- name: Run tests
     # run: |
      #    pytest 
    #- name: Login to Docker Hub
    # # uses: docker/login-action@v2
     # with:
       #   username: ${{ secrets.DOCKERUSER }}
      #    password: ${{ secrets.DOCKERPWD }}
     
    - name: Push service1 image to Docker hub 
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERUSER }}
         password: ${{ secrets.DOCKERPWD }}
     
    - run: |
         docker push rohalr/service1
        
    - name: Push service2 image to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERUSER }}
         password: ${{ secrets.DOCKERPWD }}
     
    - run: |
      
       docker push rohalr/service2
